# Þýðing mintstick_mintstick-is.po á Icelandic
# Icelandic translation for linuxmint
# Copyright (c) 2013 Free Software Foundation
# This file is distributed under the same license as the linuxmint package.
#
# Sveinn í Felli <sveinki@nett.is>, 2013, 2018, 2023.
msgid ""
msgstr ""
"Project-Id-Version: mintstick_mintstick-is\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2023-11-27 14:33+0000\n"
"PO-Revision-Date: 2023-02-20 12:12+0000\n"
"Last-Translator: Sveinn í Felli <sv1@fellsnet.is>\n"
"Language-Team: Icelandic\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2024-12-05 10:14+0000\n"
"X-Generator: Launchpad (build 1519c6efe8e9bd78e6c5ebf2eb5bcb040b95ad32)\n"
"Language: is\n"

#: lib/mintstick.py:312
msgid "The USB stick was formatted successfully."
msgstr "Það heppnaðist vel að forsníða USB-lykilinn."

#: lib/mintstick.py:315
#, python-format
msgid "An error occured while creating a partition on %s."
msgstr "Villa kom upp við að útbúa disksneið á %s."

#: lib/mintstick.py:317 lib/mintstick.py:427
msgid "Authentication Error."
msgstr "Villa við auðkenningu."

#: lib/mintstick.py:322 lib/mintstick.py:433
msgid "An error occurred."
msgstr "Villa kom upp."

#: lib/mintstick.py:420
msgid "The image was successfully written."
msgstr "Það heppnaðist vel að skrifa diskmyndina."

#: lib/mintstick.py:423
msgid "Not enough space on the USB stick."
msgstr "Ekki nógu mikið pláss eftir á USB-lyklinum."

#: lib/mintstick.py:425
msgid "An error occured while copying the image."
msgstr "Villa kom upp við að afrita diskmyndina."

#: lib/verify.py:54
msgid "bytes"
msgstr "bæti"

#: lib/verify.py:54
msgid "KB"
msgstr "KB"

#: lib/verify.py:54
msgid "MB"
msgstr "MB"

#: lib/verify.py:54
msgid "GB"
msgstr "GB"

#: lib/verify.py:54
msgid "TB"
msgstr "TB"

#: lib/verify.py:87
msgid "ISO images"
msgstr "ISO-diskmyndir"

#: lib/verify.py:91
msgid "Checksum files"
msgstr "Gátsummuskrár"

#: lib/verify.py:95
msgid "GPG signatures"
msgstr "GPG-undirritanir"

#: lib/verify.py:107 lib/verify.py:108 lib/verify.py:109
msgid "Calculating..."
msgstr "Reikna..."

#: lib/verify.py:167
msgid "No volume ID found"
msgstr "Ekkert auðkenni sýndardisks fannst"

#: lib/verify.py:208
msgid "The checksum is correct"
msgstr "Gátsumman er rétt"

#: lib/verify.py:209
msgid ""
"The checksum is correct but the authenticity of the sum was not verified."
msgstr "Gátsumman er rétt en uppruni gátsummunar var ekki sannvottaður."

#: lib/verify.py:211
msgid "Checksum mismatch"
msgstr "Gátsumma stemmir ekki"

#: lib/verify.py:212
msgid "Download the ISO image again. Its checksum does not match."
msgstr "Sæktu ISO-diskmyndina aftur. Gátsumma hennar samsvarar ekki."

#: lib/verify.py:223
msgid "The sums file could not be downloaded. Check the URL."
msgstr "Ekki var hægt að sækja gátsummuskrána. Yfirfarðu slóðina."

#: lib/verify.py:232
msgid "The gpg file could not be downloaded. Check the URL."
msgstr "Ekki var hægt að sækja gpg-skrána. Yfirfarðu slóðina."

#: lib/verify.py:243
msgid "The sums file could not be checked."
msgstr "Ekki var hægt að athuga gátsummuskrána"

#: lib/verify.py:250
msgid "The gpg file could not be checked."
msgstr "Ekki var hægt að athuga gpg-skrána."

#: lib/verify.py:260
msgid "Integrity check failed"
msgstr "Athugun á áreiðanleika mistókst"

#: lib/verify.py:269
msgid "The SHA256 sums file is not signed."
msgstr "SHA256-gátsummuskráin er ekki undirrituð."

#: lib/verify.py:273
#, python-format
msgid "Signed by: %s"
msgstr "Undirritað af: %s"

#: lib/verify.py:287
msgid "Unknown signature"
msgstr "Óþekkt undirritun"

#: lib/verify.py:288
msgid "Key not found on keyserver."
msgstr "Dulritunarlykill fannst ekki á lyklaþjóni."

#: lib/verify.py:299 lib/verify.py:305
msgid "Everything looks good!"
msgstr "Allt lítur vel út!"

#: lib/verify.py:300
msgid "This is an official ISO image."
msgstr "Þetta er opinber ISO-diskmynd."

#: lib/verify.py:306
msgid "This ISO image is verified by a trusted signature."
msgstr "Þessi diskmynd er sannvottuð með treystri undirritun."

#: lib/verify.py:309
msgid "If you trust the signature you can trust the ISO."
msgstr "Ef þú treystir undirrituninni þá geturðu treyst ISO-diskmyndinni."

#: lib/verify.py:310
msgid "Untrusted signature"
msgstr "Ótreyst undirritun"

#: lib/verify.py:311
msgid "This ISO image is verified by an untrusted signature."
msgstr "Þessi diskmynd er sannvottuð með vantreystri undirritun."

#: lib/verify.py:316
msgid "An error occurred"
msgstr "Villa kom upp"

#: lib/verify.py:327
msgid "The SHA256 sum of the ISO image is incorrect."
msgstr "SHA256-gátsumma ISO-diskmyndarinnar er ekki rétt."

#: lib/verify.py:328
msgid "The SHA256 sums file does not contain sums for this ISO image."
msgstr ""
"SHA256-gátsummuskráin inniheldur ekki gátsummur fyrir þessa ISO-diskmynd."

#: generate_additional_files.py:22 generate_additional_files.py:34
#: share/mintstick/mintstick.ui.h:38
msgid "USB Image Writer"
msgstr "USB-diskmyndaskrifari"

#: generate_additional_files.py:22 generate_additional_files.py:34
#: generate_additional_files.py:67 share/mintstick/mintstick.ui.h:39
msgid "Make a bootable USB stick"
msgstr "Búa til ræsanlegan USB-lykil"

#: generate_additional_files.py:46 generate_additional_files.py:58
#: share/mintstick/mintstick.ui.h:27
msgid "USB Stick Formatter"
msgstr "USB-forsníðingatól"

#: generate_additional_files.py:46 generate_additional_files.py:58
#: generate_additional_files.py:77 share/mintstick/mintstick.ui.h:28
msgid "Format a USB stick"
msgstr "Forsníða USB-lykil"

#: generate_additional_files.py:67
msgid "Make bootable USB stick"
msgstr "Búa til ræsanlegan USB-lykil"

#: generate_additional_files.py:77 share/mintstick/mintstick.ui.h:26
msgid "Format"
msgstr "Forsníða"

#: generate_additional_files.py:86 share/mintstick/mintstick.ui.h:32
#: share/mintstick/verify.ui.h:7
msgid "Verify"
msgstr "Sannreyna"

#: generate_additional_files.py:86 share/mintstick/mintstick.ui.h:33
msgid "Verify the authenticity and integrity of the image"
msgstr "Sannreydu uppruna og áreiðanleika diskmyndarinnar"

#: generate_additional_files.py:115 generate_additional_files.py:144
msgid ""
"This will destroy all data on the USB stick, are you sure you want to "
"proceed?"
msgstr ""
"Þetta mun eyða öllum gögnum á USB-lyklinum, ertu viss um að þú viljir halda "
"áfram?"

#: share/mintstick/mintstick.ui.h:1
msgid "USB stick:"
msgstr "USB-lykill:"

#: share/mintstick/mintstick.ui.h:2
msgid "Filesystem:"
msgstr "Skráakerfi:"

#: share/mintstick/mintstick.ui.h:3
msgid "Select a USB stick"
msgstr "Veldu USB-lykil"

#: share/mintstick/mintstick.ui.h:4
msgid ""
"FAT32 \n"
"  + Compatible everywhere.\n"
"  -  Cannot handle files larger than 4GB.\n"
"\n"
"exFAT\n"
"  + Compatible almost everywhere.\n"
"  + Can handle files larger than 4GB.\n"
"  -  Not as compatible as FAT32.\n"
"\n"
"NTFS \n"
"  + Compatible with Windows.\n"
"  -  Not compatible with Mac and most hardware devices.\n"
"  -  Occasional compatibility problems with Linux (NTFS is proprietary and "
"reverse engineered).\n"
"\n"
"EXT4 \n"
"  + Modern, stable, fast, journalized.\n"
"  + Supports Linux file permissions.\n"
"  -  Not compatible with Windows, Mac and most hardware devices.\n"
msgstr ""
"FAT32 \n"
"   + Allstaðar samhæft.\n"
"   -  Meðhöndlar ekki skrár stærri en 4GB.\n"
"\n"
"exFAT \n"
"   + Allstaðar samhæft.\n"
"   + Meðhöndlar skrár stærri en 4GB.\n"
"   -  Ekki eins samhæfanlegt og FAT32.\n"
"\n"
"NTFS \n"
"  + Samhæft við Windows.\n"
"   - Ekki samhæft við Mac eða megnið af vélbúnaði.\n"
"   - Einstaka samhæfingarvandamál við Linux (NTFS er séreignarbúnaður sem \n"
"þarf að afturábakvinna til að virki annarsstaðar).\n"
"\n"
"EXT4 \n"
"\n"
"  + Nútímalegt, stöðugt, hraðvirkt, dagbókarfært.\n"
"  + Styður skráaheimildakerfi Linux.\n"
"   - Ekki samhæft við Windows, Mac eða megnið af vélbúnaði.\n"

#: share/mintstick/mintstick.ui.h:23
msgid "Volume label:"
msgstr "Heiti á gagnahirslu:"

#: share/mintstick/mintstick.ui.h:24
msgid "Choose a name for your USB Stick"
msgstr "Veldu nafn á USB-lykilinn þinn"

#: share/mintstick/mintstick.ui.h:25
msgid "USB Stick"
msgstr "USB-lykill"

#: share/mintstick/mintstick.ui.h:29
msgid "ISO image:"
msgstr "ISO-diskmynd:"

#: share/mintstick/mintstick.ui.h:30
msgid "Select an image"
msgstr "Veldu diskmynd"

#: share/mintstick/mintstick.ui.h:31
msgid "Select Image"
msgstr "Veldu diskmynd"

#: share/mintstick/mintstick.ui.h:34
msgid "Write"
msgstr "Skrifa"

#: share/mintstick/mintstick.ui.h:35
msgid "This ISO looks like a Windows image."
msgstr "Þessi diskmynd lítur út fyrir að vera Windows-diskmynd."

#: share/mintstick/mintstick.ui.h:36
msgid "Windows images require special processing."
msgstr "Windows-diskmyndir krefjast sérstakrar meðhöndlunar."

#: share/mintstick/mintstick.ui.h:37
msgid "More information"
msgstr "Nánari upplýsingar"

#: share/mintstick/verify.ui.h:1
msgid "ISO:"
msgstr "ISO:"

#: share/mintstick/verify.ui.h:2
msgid "Volume:"
msgstr "Gagnarými:"

#: share/mintstick/verify.ui.h:3
msgid "SHA256sum:"
msgstr "SHA256summa:"

#: share/mintstick/verify.ui.h:4
msgid "Size:"
msgstr "Stærð:"

#: share/mintstick/verify.ui.h:5
msgid "SHA256 sums file:"
msgstr "SHA256-gátsummuskrá:"

#: share/mintstick/verify.ui.h:6
msgid "GPG signed file:"
msgstr "GPG-undirrituð skrá:"

#: share/mintstick/verify.ui.h:8
msgid "URLs"
msgstr "Slóðir"

#: share/mintstick/verify.ui.h:9
msgid "SHA256 sums file"
msgstr "SHA256-gátsummuskrá"

#: share/mintstick/verify.ui.h:10
msgid "GPG signed file"
msgstr "GPG-undirrituð skrá"

#: share/mintstick/verify.ui.h:11
msgid "Local files"
msgstr "Staðværar skrár"

#: share/mintstick/verify.ui.h:12
msgid "SHA256 sum"
msgstr "SHA256-gátsumma"

#: share/mintstick/verify.ui.h:13
msgid "Check"
msgstr "Athuga"

#: share/mintstick/verify.ui.h:14
msgid "Checksum"
msgstr "Gátsumma"

#: share/mintstick/verify.ui.h:15
msgid "Go back"
msgstr "Fara til baka"

#: share/mintstick/verify.ui.h:16
msgid "ISO Verification"
msgstr "ISO-sannvottun"
